# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90848d3d2c58034a2ac0be9a0ec9733ad887727900d16cd27cf0b8a0db20641616e1ef8aa90da7508c037442d7a18bdeabfc542a5c445f16486f15290874382d

test:
  secret_key_base: 92d3275e33fd0f328f9e4cc24ffddf27093bddde0686a5f5ddb93873a8328c6b10ea264d2664d57c7a2ca2564c208d66ad2bb6b80c7d4fbbee6fae280b382555

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
